[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["libreoffice", "fonts-noto-cjk", "fonts-noto-cjk-extra"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
