[phases.setup]
nixPkgs = ["nodejs_20"]
nixLibs = ["nspr", "nss", "alsa-lib", "mesa", "pango", "cairo", "cups", "libdrm", "libxkbcommon", "at-spi2-atk", "glib", "gtk3", "dbus", "expat", "xorg.libX11", "xorg.libxcb", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libXtst", "xorg.libXi", "xorg.libXcursor", "xorg.libXss"]
aptPkgs = [
  "fonts-noto-cjk",
  "fonts-liberation"
]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm ci"]

[phases.build]
cmds = ["npx prisma generate && npx next build"]

[start]
cmd = "npm start"
