[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["libreoffice-writer", "libreoffice-common", "fonts-noto-cjk"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate && npx next build"]

[start]
cmd = "npm start"
